### ISSUE TITLE
Own Display.

### ISSUE THREAD

**Issue by uwejan** [l0nelybyte/rxscreen#1]
Hello @27justin ,

Is there any update on this feature `Graphics, to allow creating own displays and drawing on them.`
I really need to create a virtual display.

**Comment by 27justin** [comment]
Hello @uwejan, I do have some very rudimentary features for graphics implemented in the library.

However, this API is not yet exposed publicly, you can take a look at the source code for it here: [graphics.rs](https://github.com/27justin/rxscreen/blob/master/src/graphics.rs).
The API currently allows you to create an X11 window and then draw `XImage`'s to it. Since the `XImage` struct just contains a buffer of uncompressed Bgr8 pixels, you should, in theory, be able to draw whatever you want to the window. 

Is this what you are looking for? If so, I don't mind creating a new branch that exposes the API publicly, so you can use it.

**Comment by uwejan** [comment]
@27justin I am going to run some tests soon. Imagine while taking the scrren shot you already expect a physical display connected to the computer, in my cas thre is no display think of a headless VM.
If your implementation does just that, i would really appreciate it,  and i would like to see the code please.

**Comment by 27justin** [comment]
@uwejan 
Do you want to draw to the x11 screen, or take screenshots of an entire x11 session?

In the latter case, there's no need for the `graphics` or `xrandr` feature, you can directly capture screenshots (or instantiate an SHM session) of the entire Display using [`Display::capture`](https://docs.rs/rxscreen/0.1.5/rxscreen/struct.Display.html#method.capture).
This function returns an Image of everything that the X11 server displayed, agnostic of monitors.

**Comment by uwejan** [comment]
I just got to my pc, just now cloned the repo, it does not seem to work. 
```
// rxscreen = { version = "0.1.5" , features  = [ "save", "shm", "xrandr"]}

use rxscreen::Display;

fn main() {
    let d = rxscreen::Display::new(":0.0");
    if let Ok(display) = d {
        let screen = display.screenshot().unwrap();
        screen.save_as("./image.png").unwrap();
        println!("Saved to file");
    }else{
        println!("Couldn't open screen.");
    }
}


error[E0599]: no method named `screenshot` found for struct `rxscreen::Display` in the current scope
 --> examples/take-raw-screenshot.rs:6:30
  |
6 |         let screen = display.screenshot().unwrap();
  |                              ^^^^^^^^^^ method not found in `rxscreen::Display`

For more information about this error, try `rustc --explain E0599`.

```

> Do you want to draw to the x11 screen, or take screenshots of an entire x11 session?
take screenshot while there is not a physical monitor connected. Something like `xvfb-run`. Or image a headless rasbery pi. If i could get the repo examples to work i will be able to test on one of my headless vms.

**Comment by 27justin** [comment]
@uwejan 
I was able to reproduce your error - my mistake, I hadn't updated the examples after updating the repo.
The function was renamed from `Display::screenshot` to `Display::capture`.

Thus, the current correct example is this:
```rust
use rxscreen::Display;
fn main() {
    let d = rxscreen::Display::new(":0.0");
    if let Ok(display) = d {
        let screen = display.capture().unwrap();
        screen.save_as("./image.png").unwrap();
        println!("Saved to file");
    }else{
        println!("Couldn't open screen.");
    }
}
```

Thanks for that, I updated the crate to version 0.1.6, which should fix your error, and one subsequent error.

**Comment by uwejan** [comment]
@27justin No worries, Thank you for quick response.
now am getting;
`"Couldn't open screen."` I am on linux running X11 though. Any chance we could continue this conversation on discord please?

**Comment by 27justin** [comment]
@uwejan Sure, feel free to add me: justinn#0027
